name: Biên Dịch Menu PvZ Fusion iOS

on:
  workflow_dispatch: # Kích hoạt nút bấm chạy thủ công

jobs:
  build:
    runs-on: macos-14 # Sử dụng môi trường máy Mac tiêu chuẩn ổn định

    steps:
    - name: Tải mã nguồn từ kho lưu trữ
      uses: actions/checkout@v4
      with:
        submodules: false # Tắt tính năng submodule tự động để tránh lỗi 128

    - name: Thiết lập môi trường và Tạo ldid giả lập
      run: |
        # 1. Tạo một lệnh ldid giả để đánh lừa hệ thống Theos vượt qua bước ký mã
        sudo echo '#!/bin/sh' > /usr/local/bin/ldid
        sudo echo 'echo "Fake ldid: Bẻ hướng ký mã thành công!"' >> /usr/local/bin/ldid
        sudo chmod +x /usr/local/bin/ldid

        # 2. Tải hệ thống khung biên dịch Theos
        git clone --recursive https://github.com/theos/theos.git ~/theos
        
        # 3. Tải trực tiếp gói SDK iOS từ máy chủ lưu trữ
        curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip master.zip
        mv sdks-master/* ~/theos/sdks/
        
        # 4. Đăng ký các biến đường dẫn vào hệ thống máy ảo
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Tiến hành đóng gói và xuất file dylib thành phẩm
      run: |
        export THEOS=$HOME/theos
        # Ép biên dịch và tạo sản phẩm
        make FINALPACKAGE=1
