name: Biên Dịch Menu PvZ Fusion iOS

on:
  workflow_dispatch: # Kích hoạt nút bấm chạy thủ công

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Tải mã nguồn từ kho lưu trữ
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Thiết lập môi trường biên dịch
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
        unzip master.zip
        mv sdks-master/* ~/theos/sdks/
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Tiến hành đóng gói và xuất file dylib thành phẩm
      run: |
        export THEOS=$HOME/theos
        make FINALPACKAGE=1

    # BƯỚC MỚI THÊM: Sử dụng công cụ codesign chính thức của Apple trên máy ảo để ký Ad-hoc cho file dylib
    - name: Ký chứng chỉ bảo mật Ad-hoc tự động
      run: |
        echo "Tiến hành ký Ad-hoc (cdhash) cho file thành phẩm..."
        find .theos/obj/ -name "*.dylib" -exec codesign -f -s - {} \;

    - name: Đẩy file dylib thành phẩm lên Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Menu-PvZ-Fusion-iOS
        path: |
          .theos/obj/**/*.dylib
          packages/*.deb
